name: sdg_app2
description: A new Flutter project.
version: 0.0.1+0.0.1

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html


environment:
  sdk: ">=2.16.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
    
    


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  
  flutter_svg: ^1.0.3 # help us to use SVG in our app
  provider: ^6.0.0 # for State management
  flutter_swiper: ^1.1.6
  animated_theme_switcher: "^2.0.5"
  firebase_auth: ^3.3.9
  google_sign_in: ^5.0.3
  font_awesome_flutter: ^9.0.0
  url_launcher: ^5.0.2
  link: ^1.1.0
  http: ^0.13.4
  # flutter_stripe: ^2.3.0
  flutter_native_splash: ^2.1.0
  flutter_launcher_icons: ^0.9.2
  webview_flutter: ^3.0.1
  flutter_staggered_grid_view: ^0.6.1
  shared_preferences: ^2.0.13
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  get_it: ^7.2.0
  

  



dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

flutter_icons:
  image_path: assets/images/logo.png
  andriod: true
  ios: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: assets/images/1024.png
  
  
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash1.png
  andriod: true
  ios: true


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true
  uses-material-design: true
  assets:
     - assets/images/
     - assets/icons/

  fonts:
     - family: Quicksand
       fonts:
         - asset: assets/fonts/Quicksand/Quicksand-Regular.ttf
         - asset: assets/fonts/Quicksand/Quicksand-Bold.ttf
           weight: 700
         - asset: assets/fonts/Quicksand/Quicksand-Light.ttf
           weight: 300

# flutter_intl:                                   # Add this line
#   enabled: true                                 # Add this line
#   class_name: I10n                              # Add this line
#   main_locale: en                               # Add this line
#   arb_dir: lib/provider/L10/L10.dart          # Add this line
#   output_dir: .dart_tool/flutter_gen/gen_l10n   # Add this line
 
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
